/**
 * Copied on 07/03/2025 from https://github.com/containers/podman/blob/d1a3f96cbf08544093e9ad3acec1c28d858f707a/pkg/systemd/quadlet/quadlet.go#L58
 */
export enum ALL_KEYS {
  KeyAddCapability = 'AddCapability',
  KeyAddDevice = 'AddDevice',
  KeyAddHost = 'AddHost',
  KeyAllTags = 'AllTags',
  KeyAnnotation = 'Annotation',
  KeyArch = 'Arch',
  KeyAuthFile = 'AuthFile',
  KeyAutoUpdate = 'AutoUpdate',
  KeyCertDir = 'CertDir',
  KeyCgroupsMode = 'CgroupsMode',
  KeyConfigMap = 'ConfigMap',
  KeyContainerName = 'ContainerName',
  KeyContainersConfModule = 'ContainersConfModule',
  KeyCopy = 'Copy',
  KeyCreds = 'Creds',
  KeyDecryptionKey = 'DecryptionKey',
  KeyDefaultDependencies = 'DefaultDependencies',
  KeyDevice = 'Device',
  KeyDisableDNS = 'DisableDNS',
  KeyDNS = 'DNS',
  KeyDNSOption = 'DNSOption',
  KeyDNSSearch = 'DNSSearch',
  KeyDriver = 'Driver',
  KeyDropCapability = 'DropCapability',
  KeyEntrypoint = 'Entrypoint',
  KeyEnvironment = 'Environment',
  KeyEnvironmentFile = 'EnvironmentFile',
  KeyEnvironmentHost = 'EnvironmentHost',
  KeyExec = 'Exec',
  KeyExitCodePropagation = 'ExitCodePropagation',
  KeyExposeHostPort = 'ExposeHostPort',
  KeyFile = 'File',
  KeyForceRM = 'ForceRM',
  KeyGateway = 'Gateway',
  KeyGIDMap = 'GIDMap',
  KeyGlobalArgs = 'GlobalArgs',
  KeyGroup = 'Group',
  KeyGroupAdd = 'GroupAdd',
  KeyHealthCmd = 'HealthCmd',
  KeyHealthInterval = 'HealthInterval',
  KeyHealthLogDestination = 'HealthLogDestination',
  KeyHealthMaxLogCount = 'HealthMaxLogCount',
  KeyHealthMaxLogSize = 'HealthMaxLogSize',
  KeyHealthOnFailure = 'HealthOnFailure',
  KeyHealthRetries = 'HealthRetries',
  KeyHealthStartPeriod = 'HealthStartPeriod',
  KeyHealthStartupCmd = 'HealthStartupCmd',
  KeyHealthStartupInterval = 'HealthStartupInterval',
  KeyHealthStartupRetries = 'HealthStartupRetries',
  KeyHealthStartupSuccess = 'HealthStartupSuccess',
  KeyHealthStartupTimeout = 'HealthStartupTimeout',
  KeyHealthTimeout = 'HealthTimeout',
  KeyHostName = 'HostName',
  KeyImage = 'Image',
  KeyImageTag = 'ImageTag',
  KeyInternal = 'Internal',
  KeyIP = 'IP',
  KeyIP6 = 'IP6',
  KeyIPAMDriver = 'IPAMDriver',
  KeyIPRange = 'IPRange',
  KeyIPv6 = 'IPv6',
  KeyKubeDownForce = 'KubeDownForce',
  KeyLabel = 'Label',
  KeyLogDriver = 'LogDriver',
  KeyLogOpt = 'LogOpt',
  KeyMask = 'Mask',
  KeyMount = 'Mount',
  KeyNetwork = 'Network',
  KeyNetworkAlias = 'NetworkAlias',
  KeyNetworkName = 'NetworkName',
  KeyNoNewPrivileges = 'NoNewPrivileges',
  KeyNotify = 'Notify',
  KeyOptions = 'Options',
  KeyOS = 'OS',
  KeyPidsLimit = 'PidsLimit',
  KeyPod = 'Pod',
  KeyPodmanArgs = 'PodmanArgs',
  KeyPodName = 'PodName',
  KeyPublishPort = 'PublishPort',
  KeyPull = 'Pull',
  KeyReadOnly = 'ReadOnly',
  KeyReadOnlyTmpfs = 'ReadOnlyTmpfs',
  /**
   * @deprecated
   */
  KeyRemapGid = 'RemapGid',
  /**
   * @deprecated
   */
  KeyRemapUid = 'RemapUid',
  /**
   * @deprecated
   */
  KeyRemapUidSize = 'RemapUidSize',
  /**
   * @deprecated
   */
  KeyRemapUsers = 'RemapUsers',
  KeyRootfs = 'Rootfs',
  KeyRunInit = 'RunInit',
  KeySeccompProfile = 'SeccompProfile',
  KeySecret = 'Secret',
  KeySecurityLabelDisable = 'SecurityLabelDisable',
  KeySecurityLabelFileType = 'SecurityLabelFileType',
  KeySecurityLabelLevel = 'SecurityLabelLevel',
  KeySecurityLabelNested = 'SecurityLabelNested',
  KeySecurityLabelType = 'SecurityLabelType',
  KeyServiceName = 'ServiceName',
  KeySetWorkingDirectory = 'SetWorkingDirectory',
  KeyShmSize = 'ShmSize',
  KeyStartWithPod = 'StartWithPod',
  KeyStopSignal = 'StopSignal',
  KeyStopTimeout = 'StopTimeout',
  KeySubGIDMap = 'SubGIDMap',
  KeySubnet = 'Subnet',
  KeySubUIDMap = 'SubUIDMap',
  KeySysctl = 'Sysctl',
  KeyTarget = 'Target',
  KeyTimezone = 'Timezone',
  KeyTLSVerify = 'TLSVerify',
  KeyTmpfs = 'Tmpfs',
  KeyType = 'Type',
  KeyUIDMap = 'UIDMap',
  KeyUlimit = 'Ulimit',
  KeyUnmask = 'Unmask',
  KeyUser = 'User',
  KeyUserNS = 'UserNS',
  KeyVariant = 'Variant',
  KeyVolatileTmp = 'VolatileTmp', // deprecated
  KeyVolume = 'Volume',
  KeyVolumeName = 'VolumeName',
  KeyWorkingDir = 'WorkingDir',
  KeyYaml = 'Yaml',
}
